### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by ilvrak** [digitalshadowhawk/BiomeBordersRevived#3]
mod-biomebordersrevived-1.1.0-mc1.12.1.litemod
not loading on 1.12.2

**Comment by FusionLord** [comment]
In theory you can rename the file to '.zip' and open it, extract the 'litemod.json' change the 'mcversion' inside and save, lastly copy the new file back into the '.zip' and change the file back into a '.litemod'. and it `should` load.

**Comment by ilvrak** [comment]
it loads that way! thanx!
